apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault

resources:
  - namespace.yaml
  - vault-deployment.yaml
  - vault-service.yaml
  # - vault-config.yaml  # Optional, if using a ConfigMap
  - vault-ingress.yaml  # Optional, if using Ingress
