apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: vault
  namespace: flux-system
spec:
  interval: 10m
  path: "./clusters/my-cluster/vault"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
